export const strings = {
  appName: 'SafarPlug',
  splash: {
    tagline: 'Empowering Your EV Journeys Across India',
  },
  auth: {
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to access stations, plan trips, and charge your EV',
    registerTitle: 'Create Account',
    registerSubtitle: 'Join SafarPlug to find and book charging slots',
    emailPlaceholder: 'Email Address',
    passwordPlaceholder: 'Password',
    namePlaceholder: 'Full Name',
    phonePlaceholder: 'Mobile Number',
    vehicleType: 'Primary Vehicle Type',
    loginBtn: 'Login',
    registerBtn: 'Sign Up',
    noAccount: "Don't have an account? Sign Up",
    hasAccount: 'Already have an account? Login',
  },
  home: {
    searchPlaceholder: 'Search charging stations...',
    filterAll: 'All',
    filterFast: 'Fast Charger',
    filterAvailable: 'Available Now',
    filterTwoWheeler: '2-Wheeler Friendly',
    nearbyHeader: 'Nearby Charging Stations',
  },
  stationDetail: {
    about: 'About Station',
    chargers: 'Available Chargers',
    reviews: 'Reviews & Feedback',
    startCharge: 'Start Charging Session',
    amenities: 'Amenities',
  },
  tripPlanner: {
    title: 'EV Trip Planner',
    subtitle: 'Plan your route with optimal charging stops',
    startLocation: 'Starting Point',
    endLocation: 'Destination',
    batteryLevel: 'Current Battery Level (%)',
    planBtn: 'Calculate Route',
  },
  charging: {
    title: 'Charging Session',
    connecting: 'Connecting to Charger...',
    active: 'Charging Active',
    completed: 'Session Completed',
    stopBtn: 'Stop Charging',
    summary: 'Charging Summary',
  },
};
